FROM registry.cn-hangzhou.aliyuncs.com/kennylee/opencv:openjdk-jdk8

MAINTAINER kennylee <kennylee26@gmail.com>

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT "/entrypoint.sh"
