FROM registry.cn-hangzhou.aliyuncs.com/kennylee/java:openjdk-8-jre

MAINTAINER kennylee <kennylee26@gmail.com>

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT "/entrypoint.sh"
