# see also: https://github.com/openzipkin/zipkin/blob/master/docker/Dockerfile
FROM openzipkin/zipkin

MAINTAINER kennylee <kennylee26@gmail.com>

ENV TZ=Asia/Shanghai

EXPOSE 9410 9411

# Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables